### ISSUE TITLE
Add blue bar at top of site

### ISSUE THREAD

**Issue by wpalchemist** [wpalchemist/tfc-nathan-small#1]
content controllable via customizer

**Comment by apennell** [comment]
@wpalchemist the text is supposed to be a link. Do you want to update that? Can we change it so that the customizer accepts a link and link text?

**Comment by wpalchemist** [comment]
@apennell You can just type HTML into that textarea to make the link

**Comment by apennell** [comment]
Ooooh cool!

**Comment by apennell** [comment]
This is essentially complete but will require adding <a href="https://donaanacounty.org/elections" class="white-link" target="_blank">Click here for the latest voting information</a> to the "Blue bar text" option in the TFC theme section of the customizer, once the staging site is updated to include that option.
