### ISSUE TITLE
Style blockquote

### ISSUE THREAD

**Issue by wpalchemist** [wpalchemist/tfc-nathan-small#15]

**Comment by apennell** [comment]
@wpalchemist What is this referring to?

**Comment by apennell** [comment]
This is essentially complete but will require adding `<a href="https://donaanacounty.org/elections" class="white-link" target="_blank">Click here for the latest voting information</a>` to the "Blue bar text" option in the TFC theme section of the customizer, once the staging site is updated to include that option.

**Comment by apennell** [comment]
Complete
