### ISSUE TITLE
Adjust styling of homepage featured image and content

### ISSUE THREAD

**Issue by wpalchemist** [wpalchemist/tfc-nathan-small#2]

**Comment by apennell** [comment]
@wpalchemist We need to remove the "entry title" from the heading on the home page so that it doesn't say "Home"

**Comment by apennell** [comment]
@wpalchemist The Gutenberg generated buttons are adding classes with styling that is messing up the styling of the button classes that I made and I’m not sure what the best way to go about button styling in this case. I ran into problems when I started trying to updated the buttons in the header. Gutenberg creates a button that’s an `a` wrapped in a `div` and the custom classes you can add go in the div, which results in the div being style with my button styles, padding at all, and the `a` inside it being styled like their buttons, padding and all.

**Comment by wpalchemist** [comment]
@apennell To style the Gutenberg buttons, you'll just have to write some really ugly CSS.

**Comment by wpalchemist** [comment]
I have removed the entry title from the home page

**Comment by apennell** [comment]
Thanks! The only place I had trouble styling the Gutenberg buttons was in this spot, which was placing the class in a different element than the others. With a day's distance from it, I thought of the slightly obvious solution of a slightly different class name for instances like this so I'll take care of that.

**Comment by apennell** [comment]
Fixed the buttons and pushed code up so closing this out
