### ISSUE TITLE
Add social media bar below featured image

### ISSUE THREAD

**Issue by wpalchemist** [wpalchemist/tfc-nathan-small#3]

**Comment by apennell** [comment]
Completed styling and merged with master.

**Comment by apennell** [comment]
@wpalchemist Can we change the size of the social icon svg's? In the mobile designs that Frances just added to Zeplin I was able to get a better idea of the sizes the elements should be and these should be a bit smaller, about 38px. I'm not sure how you got the svg paths that are in panel-page.php but I didn't see a clear way to update!

**Comment by wpalchemist** [comment]
@apennell You should be able to resize them with CSS?  But I think we're going to get rid of this section anyway, so it's not worth spending time on it until we get more design feedback.

**Comment by apennell** [comment]
I'm going to close this out because it's basically completed as per the current design. We can open a new ticket (or re-open) if changes are requested.
