### ISSUE TITLE
Add additional fields to "Issues" on home page

### ISSUE THREAD

**Issue by apennell** [wpalchemist/tfc-nathan-small#30]
2 additional fields were added that weren't in the original design. Also need to add the "Read More" link in the third column of that new row. @wpalchemist Do you want to add this and have me finish up the style? Otherwise I think it's something I can just take care of.

**Comment by wpalchemist** [comment]
This content is all in the page content for the home page - all you have to do is edit the home page to add more items.

**Comment by apennell** [comment]
Done
