### ISSUE TITLE
Issues page

### ISSUE THREAD

**Issue by apennell** [wpalchemist/tfc-nathan-small#31]
The stand-alone issues page is separate from and a bit different than the issues section on the home page (has more content per issue, no links, full-width columns), so I don't think we should be re-using that same page (partial? whatever WP calls it 😁). 

Needs content added to page then needs to be styled.

**Comment by apennell** [comment]
I think two columns is the way to go actually and I need to change the css for the columns.

**Comment by wpalchemist** [comment]
Yeah, there isn't an easy way to do this, unfortunately.  I think that using CSS to change the width of the columns is probably the best way to go. Alternatively, I could make a custom Gutenberg block, but that's quite a bit of work.  If changing column size with CSS gets complicated, let me know.

Gutenberg does let you add custom CSS classes to blocks, so I would use that to target these columns.  Let me know if you can't find that.

**Comment by apennell** [comment]
I was able to get one to work but manipulating the css in the browser
inspector before signing off last night, so I should be able to get that to
work with adding custom classes, I think! However, it looked like it still
thinks there’s the side bar and isn’t putting in the class that makes it
full width if it’s not there. I couldn’t find where in the layout to turn
that off.
