### ISSUE TITLE
Add "Get Involved" section above footer

### ISSUE THREAD

**Issue by wpalchemist** [wpalchemist/tfc-nathan-small#6]

**Comment by wpalchemist** [comment]
On the staging site, I added widgets to create this section (under Appearance-->Widgets, in the "top footer" widget area).  It might be easier to re-order the widgets so the donate button is first.  That should give you all the HTML you need to match the design, but if it would be easier to hard-code this, let me know.

**Comment by apennell** [comment]
I ended up removing the text widgets and replacing with a custom html one for the content and an image one for the background image, which I styled with CSS to be a background banner image. I updated this on staging as well. Closing this out as complete, although it looks terrible on staging until the CSS is added there!

**Comment by apennell** [comment]
Reopening this, since we talked about turning into a customizable element instead. @wpalchemist assigning to you, then you can assign to me once it's ready for styling.

**Comment by wpalchemist** [comment]
I have changed this section so it is controlled with the theme customizer.  I removed the widgets, and updated the content in the customizer, so this is ready for style.

**Comment by apennell** [comment]
Done, thanks!
