### ISSUE TITLE
Style footer widgets

### ISSUE THREAD

**Issue by wpalchemist** [wpalchemist/tfc-nathan-small#7]

**Comment by wpalchemist** [comment]
I added widgets on the staging site in the bottom footer area.  The contact form is a Jetpack contact form. The Facebook widget is a Jetpack page feed widget - you can adjust the width and height in the widget settings.

**Comment by apennell** [comment]
@wpalchemist I can't seem to access the Jetpack widgets locally. I added the Jetpack plugin, but the additional widgets aren't showing up in the widget section of the admin area or as available in the add widget part of the customizer. Initially I got an error about not being able to use it in a local environment so I added `const JETPACK_DEV_DEBUG = TRUE;` to wp-config.php, which removed that error but didn't get the widgets to appear. I've reached the end of my of Googling abilities. Is it possible to get these locally or do I just need to edit it on staging?

**Comment by apennell** [comment]
Although I didn't do this with the widgets available locally, styling was only necessary for the contact widget and I was able to do that without adding it on my end. 

Note: I removed the line from the design that said "Other way to reach us." It's an awkward sentence and sounds wrong, although technically correct, and unnecessary.
